const BUILD_STATE_NONE = "BUILD_STATE_NONE";
const BUILD_STATE_WAITING = "BUILD_STATE_WAITING";
const BUILD_STATE_PROGRESS = "BUILD_STATE_PROGRESS";
const BUILD_STATE_WARNING = "BUILD_STATE_WARNING";
const BUILD_STATE_SUCCESS = "BUILD_STATE_SUCCESS";
const BUILD_STATE_FAIL = "BUILD_STATE_FAIL";
const BUILD_STATES = [
  BUILD_STATE_NONE,
  BUILD_STATE_WAITING,
  BUILD_STATE_PROGRESS,
  BUILD_STATE_WARNING,
  BUILD_STATE_SUCCESS,
  BUILD_STATE_FAIL,
];

module.exports = {
  BUILD_STATE_NONE,
  BUILD_STATE_WAITING,
  BUILD_STATE_PROGRESS,
  BUILD_STATE_WARNING,
  BUILD_STATE_SUCCESS,
  BUILD_STATE_FAIL,
  BUILD_STATES,
};
